baseURL = "https://services.okayugroup.com/"
languageCode = "ja"
title = "おかゆグループサービス"
theme = "docsy"

[params]
  docsyVersion = "v0.2.0"
  prism_syntax_highlighting = true
  customCSS = ["/css/custom.css"]
  [params.copyright]
    from_year = "2024"
    to_year = "2024"
    authors = "おかゆグループ"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    style = "monokai"
    noClasses = false

[module]
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false

  [[module.imports]]
    path = "github.com/FortAwesome/Font-Awesome"
    disable = false

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4
