baseURL = "https://services.okayugroup.com/"
languageCode = "ja"
title = "おかゆグループサービス"
theme = "docsy"

[params]
  docsyVersion = "v0.2.0"
  prism_syntax_highlighting = true
  customCSS = ["/css/custom.css", "https://archive.okayugroup.com/fonts/NotoSansJP-font.css"]

  [params.copyright]
    from_year = "2023"
    to_year = ""
    authors = "OkayuGroup"

[outputFormats]
  [outputFormats.html]
    mediatype = "text/html"
    baseName = "index"
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"
  [outputFormats.json]
    mediatype = "application/json"
    baseName = "json"
[markup]
  [markup.highlight]
    style = "monokai"
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      xHTML = false
      footnoteReturnLinkContents = "↩"
      footnoteAnchorPrefix = ""
      autoHeadingIDType = "github"
      autoHeadingIDSize = 6
      definitionList = true
      typographer = true
      emoji = true
      hardWraps = false

[module]
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false

  [[module.imports]]
    path = "github.com/FortAwesome/Font-Awesome"
    disable = false

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "https://okayugroup.com/contact/"
    weight = 4
